In [1]:
#Q1
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
lista=a.tolist()
print(lista)
print(lista[2])

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]
3


In [2]:
#Q2
import numpy as np
a=np.zeros(9)
a=a.tolist()
print(a)
for i in range(9):
    x=int(input('donner une valeur , '))
    a[i]=x
    #print(a)
a=np.array(a)
a=a.reshape(3,3)
print(a)
n=a.shape
s=0
for i in range(3):
    s=s+a[i,i]
print('la somme des éléments diagonaux est  :',s)



[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
donner une valeur , 1
donner une valeur , 2
donner une valeur , 3
donner une valeur , 4
donner une valeur , 5
donner une valeur , 6
donner une valeur , 7
donner une valeur , 8
donner une valeur , 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
la somme des éléments diagonaux est  : 15


In [4]:
#Q2__2
import numpy as np
from math import sqrt
l=int(input('donner le nombre total des éléments du tableau  :'))
a=np.zeros(l)
a=a.tolist()
print(a)
for i in range(l):
    x=int(input('donner une valeur , '))
    a[i]=x
    #print(a)
a=np.array(a)
c_l=sqrt(l)
print(c_l)
print('____-----____')
c_l=int(c_l)
print('---_____---__-_____-_-_-_-_-_-_')
a=a.reshape(c_l,c_l)
print(a)
n=a.shape
s=0
for i in range(c_l):
    s=s+a[i,i]
print('la somme des éléments diagonaux est  :',s)
print('---___---En utilisant TRACE---___---')
s2=a.trace()
print(s2)



donner le nombre total des éléments du tableau  :16
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
donner une valeur , 1
donner une valeur , 2
donner une valeur , 3
donner une valeur , 4
donner une valeur , 5
donner une valeur , 6
donner une valeur , 7
donner une valeur , 8
donner une valeur , 9
donner une valeur , 10
donner une valeur , 11
donner une valeur , 12
donner une valeur , 13
donner une valeur , 14
donner une valeur , 15
donner une valeur , 16
4.0
____-----____
---_____---__-_____-_-_-_-_-_-_
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
la somme des éléments diagonaux est  : 34
---___---En utilisant TRACE---___---
34


In [8]:
#Q3
import numpy as np
from math import sqrt
l=int(input('donner le nombre total des éléments du tableau  :'))
a=np.zeros(l)
a=a.tolist()
print(a)
for i in range(l):
    x=int(input('donner une valeur , '))
    a[i]=x
    #print(a)
a=np.array(a)
nbr_col=int(input('donner le nombre de colones que vous voulez  : '))
nbr_ligne=int(l/nbr_col)


#c_l=sqrt(l)
#print(c_l)
#print('____-----____')
#c_l=int(c_l)
print('---_____---__-_____-_-_-_-_-_-_')
a=a.reshape(nbr_ligne,nbr_col)
print(a)
list_val=list()
X=int(input('donner la valeur limite   :  '))
for i in range(nbr_ligne):
    for j in range(nbr_col):
        if a[i,j]>X:
            list_val.append(a[i,j])
print(list_val)
print('methode_2-----______---------')
list_val2=list()
list_val2.append(a[a>X])
print(list_val2)
type(list_val2)



donner le nombre total des éléments du tableau  :9
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
donner une valeur , 1
donner une valeur , 2
donner une valeur , 3
donner une valeur , 4
donner une valeur , 5
donner une valeur , 6
donner une valeur , 7
donner une valeur , 8
donner une valeur , 9
donner le nombre de colones que vous voulez  : 3
---_____---__-_____-_-_-_-_-_-_
[[1 2 3]
 [4 5 6]
 [7 8 9]]
donner la valeur limite   :  5
[6, 7, 8, 9]
methode_2-----______---------
[array([6, 7, 8, 9])]


list

In [13]:
#Q4
import numpy as np
#from math import sqrt
l=int(input('donner le nombre total des éléments du tableau  :'))
a=np.zeros(l)
b=np.zeros(l)
c=np.zeros(l)
a=a.tolist()
b=b.tolist()
#c=c.tolist()
#print(a)
#print(b)
print('-----------------INITIA_TAB')
for i in range(l):
    x=int(input('donner une valeur pourle PREMIER tab , '))
    y=int(input('donner une valeur pourle DEUXIEME tab , '))
    a[i]=x
    b[i]=y
    #print(a)
a=np.array(a)
b=np.array(b)
nbr_col=int(input('donner le nombre de colones que vous voulez  : '))
nbr_ligne=int(l/nbr_col)
print('---_____---__-_____-_-_-_-_-_-_')
a=a.reshape(nbr_ligne,nbr_col)
b=b.reshape(nbr_ligne,nbr_col)
c=c.reshape(nbr_ligne,nbr_col)
print(a)
print(b)
print(c)
print('-_-_-_-_-_-_-_-_--_-_-_-')
for i in range(nbr_ligne):
    for j in range(nbr_col):
        c[i,j]=a[i,j]+b[i,j]
print('Tableau a  :\n',a)
print('tableau b   :\n',b)
print('la somme des deux tableaux est    :\n',c)


donner le nombre total des éléments du tableau  :9
-----------------INITIA_TAB
donner une valeur pourle PREMIER tab , 1
donner une valeur pourle DEUXIEME tab , 2
donner une valeur pourle PREMIER tab , 3
donner une valeur pourle DEUXIEME tab , 4
donner une valeur pourle PREMIER tab , 5
donner une valeur pourle DEUXIEME tab , 6
donner une valeur pourle PREMIER tab , 7
donner une valeur pourle DEUXIEME tab , 8
donner une valeur pourle PREMIER tab , 9
donner une valeur pourle DEUXIEME tab , 10
donner une valeur pourle PREMIER tab , 11
donner une valeur pourle DEUXIEME tab , 12
donner une valeur pourle PREMIER tab , 13
donner une valeur pourle DEUXIEME tab , 14
donner une valeur pourle PREMIER tab , 15
donner une valeur pourle DEUXIEME tab , 16
donner une valeur pourle PREMIER tab , 17
donner une valeur pourle DEUXIEME tab , 18
donner le nombre de colones que vous voulez  : 3
---_____---__-_____-_-_-_-_-_-_
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0. 0. 0.

In [14]:
#Q5
import numpy as np
l=int(input('donner le nombre total des éléments du tableau  :'))
a=np.zeros(l)
a=a.tolist()
print('-----------------INITIA_TAB')
for i in range(l):
    x=int(input('donner une valeur pourle PREMIER tab , '))
    a[i]=x
a=np.array(a)
nbr_col=int(input('donner le nombre de colones que vous voulez  : '))
nbr_ligne=int(l/nbr_col)
print('---_____---__-_____-_-_-_-_-_-_')
a=a.reshape(nbr_ligne,nbr_col)
print(a)
print('-_-_-_-_-_-_-_-_--_-_-_-')
np.mean(a,axis=1)

donner le nombre total des éléments du tableau  :9
-----------------INITIA_TAB
donner une valeur pourle PREMIER tab , 1
donner une valeur pourle PREMIER tab , 2
donner une valeur pourle PREMIER tab , 3
donner une valeur pourle PREMIER tab , 4
donner une valeur pourle PREMIER tab , 5
donner une valeur pourle PREMIER tab , 6
donner une valeur pourle PREMIER tab , 7
donner une valeur pourle PREMIER tab , 8
donner une valeur pourle PREMIER tab , 9
donner le nombre de colones que vous voulez  : 3
---_____---__-_____-_-_-_-_-_-_
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-_-_-_-_-_-_-_-_--_-_-_-


array([2., 5., 8.])